#!/home/linuxbrew/.linuxbrew/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

sys.path.append('/home/hujinqi/Workspaces/pythons')

from JiraTools.JiraComponents import main


if __name__ == '__main__':

    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
