#!/home/linuxbrew/.linuxbrew/bin/python3

# -*- coding: utf-8 -*-
import re
import sys
import getpass

#  1. 加入当前工程目录的上级目录
#  2. .bashrc 加入 components 文件所在目录
#  3. source 
#  4. 开始使用 components --help 了解命令信息
if getpass.getuser() == 'hujinqi':
    sys.path.append('/home/hujinqi/Workspaces/pythons')
if getpass.getuser() == 'weijuncheng':
	sys.path.append('/home/weijuncheng/tools/jiratools')

from JiraTools.JiraComponents import main


if __name__ == '__main__':

    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
