#!/home/linuxbrew/.linuxbrew/bin/python3

# -*- coding: utf-8 -*-
import re
import sys
import getpass

if getpass.getuser() == 'hujinqi':
    sys.path.append('/home/hujinqi/Workspaces/pythons')
if getpass.getuser() == 'weijuncheng':
	sys.path.append('/home/weijuncheng/tools/jiratools')

from JiraTools.JiraComponents import main


if __name__ == '__main__':

    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
